#!/bin/sh -p
set -eu

unset BASH_ENV ENV CDPATH GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY
unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_REPLACE_REF_BASE GIT_CONFIG_COUNT
unset PYTHONPATH PYTHONHOME PYTHONUSERBASE PYTHONSTARTUP PYTHONINSPECT PYTHONWARNINGS
unset PYTHONBREAKPOINT PYTHONDEBUG PYTHONMALLOC PYTHONPROFILEIMPORTTIME PYTHONSAFEPATH
unset COVERAGE_PROCESS_START COVERAGE_RCFILE COVERAGE_CORE
unset LD_PRELOAD LD_LIBRARY_PATH DYLD_INSERT_LIBRARIES DYLD_LIBRARY_PATH

SCRIPT_DIR=$(/usr/bin/dirname "$0")
case "$SCRIPT_DIR" in
    /*) ;;
    *) SCRIPT_DIR=$(/bin/pwd -P)/$SCRIPT_DIR ;;
esac
TRUSTED_HOME=/tmp/swift-sample-trusted-home
/bin/mkdir -p "$TRUSTED_HOME"
/bin/chmod 700 "$TRUSTED_HOME"

exec /usr/bin/env -i \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_NOSYSTEM=1 \
    GIT_PAGER=cat \
    GIT_TERMINAL_PROMPT=0 \
    HOME="$TRUSTED_HOME" \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=/usr/bin:/bin \
    /usr/bin/python3 -I -S -B "$SCRIPT_DIR/verify_candidate.py" "$@"
